#!/usr/bin/env python3
"""
WHOOP folder sync — NO API, no credentials needed.

Reads daily markdown files generated by obsidian-whoop-plugin from:
  ~/Documents/MyVault/sports-fitness/Health/WHOOP/2026/daily-YYYY-MM-DD.md

Writes / updates:
  - sports-fitness/workouts/history/YYYY-MM-DD.md   (one file per day)
  - sports-fitness/sleep/log.md                      (running sleep table)
  - sports-fitness/Health/WHOOP/index.md             (WHOOP hub summary table)

Usage:
  python3 whoop_folder_sync.py              # sync today only
  python3 whoop_folder_sync.py --all        # backfill all available days
  python3 whoop_folder_sync.py --date 2026-04-14   # specific date
"""

import re
import sys
from pathlib import Path
from datetime import date

# ── paths ─────────────────────────────────────────────────────────────────────

VAULT_ROOT   = Path.home() / "Documents" / "MyVault"
WHOOP_DIR    = VAULT_ROOT / "sports-fitness" / "Health" / "WHOOP" / "2026"
SECOND_BRAIN = VAULT_ROOT / "second-brain" / "sports-fitness"
HISTORY_DIR  = SECOND_BRAIN / "workouts" / "history"
SLEEP_LOG    = SECOND_BRAIN / "sleep" / "log.md"
WHOOP_INDEX  = VAULT_ROOT / "sports-fitness" / "Health" / "WHOOP" / "index.md"


# ── parsers ───────────────────────────────────────────────────────────────────

def parse_table_value(text, label):
    """Extract value from a markdown table row: | label | value |"""
    m = re.search(rf"\|\s*{re.escape(label)}\s*\|\s*([^|\n]+?)\s*\|", text)
    if not m:
        return None
    # Strip markdown bold markers (**) from the value
    return re.sub(r"\*+", "", m.group(1)).strip()


def parse_time_to_hours(time_str):
    """Convert '8h 29m' or '1h 6m' or '55m' to decimal hours, rounded to 1dp."""
    if not time_str:
        return None
    h = re.search(r"(\d+)h", time_str)
    m = re.search(r"(\d+)m", time_str)
    hours = int(h.group(1)) if h else 0
    mins  = int(m.group(1)) if m else 0
    total = hours + mins / 60
    return round(total, 1) if total > 0 else None


def parse_whoop_file(filepath):
    """
    Parse a WHOOP daily markdown file and return a dict of metrics.
    Uses only Main Sleep block for sleep metrics.
    """
    text = filepath.read_text()
    d = {}

    # ── recovery ──
    d["recovery"]  = parse_table_value(text, "Recovery Score")
    d["hrv"]       = parse_table_value(text, "HRV \\(RMSSD\\)")
    d["rhr"]       = parse_table_value(text, "Resting Heart Rate")
    d["spo2"]      = parse_table_value(text, "SpO₂")
    d["skin_temp"] = parse_table_value(text, "Skin Temp")

    # ── main sleep only ──
    # Find the Main Sleep section, then parse only up to the next ###/## heading
    main_sleep_match = re.search(r"### Main Sleep\n(.*?)(?=\n###|\n##|\Z)", text, re.DOTALL)
    if main_sleep_match:
        ms = main_sleep_match.group(1)
        in_bed_str    = parse_table_value(ms, "In Bed")
        deep_str      = parse_table_value(ms, "SWS \\(Deep\\)")
        rem_str       = parse_table_value(ms, "REM")
        d["sleep_hours"] = parse_time_to_hours(in_bed_str)
        d["sleep_perf"]  = parse_table_value(ms, "Performance")
        d["sleep_eff"]   = parse_table_value(ms, "Efficiency")
        d["deep_hours"]  = parse_time_to_hours(deep_str)
        d["rem_hours"]   = parse_time_to_hours(rem_str)
        d["resp_rate"]   = parse_table_value(ms, "Respiratory Rate")
        d["disturbances"]= parse_table_value(ms, "Disturbances")
    else:
        d["sleep_hours"] = d["sleep_perf"] = d["sleep_eff"] = None
        d["deep_hours"]  = d["rem_hours"]  = None
        d["resp_rate"]   = d["disturbances"] = None

    # ── strain ──
    strain_raw = parse_table_value(text, "Day Strain")
    if strain_raw:
        # e.g. "18.0 (All Out)" or just "18.0"
        d["strain"] = strain_raw
        m = re.match(r"([\d.]+)\s*\(?(.*?)\)?$", strain_raw)
        d["strain_val"]   = m.group(1) if m else strain_raw
        d["strain_label"] = m.group(2).strip() if m and m.group(2) else ""
    else:
        d["strain"] = d["strain_val"] = d["strain_label"] = None

    d["avg_hr"] = parse_table_value(text, "Avg Heart Rate")
    d["max_hr"] = parse_table_value(text, "Max Heart Rate")
    d["cal_kj"] = parse_table_value(text, "Calories \\(kJ\\)")

    # ── workouts ──
    workouts = re.findall(r"^### (.+)$", text, re.MULTILINE)
    # Filter out sleep section headers
    sleep_headers = {"Main Sleep", "Additional Sleep", "Nap"}
    d["workouts"] = [w for w in workouts if w not in sleep_headers]

    return d


def fmt(val, unit=""):
    if val is None or val == "" or val == "—":
        return "—"
    return f"{val}{unit}"


def recovery_emoji(recovery_str):
    if not recovery_str:
        return ""
    try:
        pct = int(recovery_str.replace("%", "").strip())
        if pct >= 67:
            return " 🟢"
        elif pct >= 34:
            return " 🟡"
        else:
            return " 🔴"
    except ValueError:
        return ""


# ── writers ───────────────────────────────────────────────────────────────────

def write_history_file(day_str, d):
    """Write/overwrite a workout history file for this day."""
    HISTORY_DIR.mkdir(parents=True, exist_ok=True)
    filepath = HISTORY_DIR / f"{day_str}.md"

    workouts_section = ""
    if d["workouts"]:
        workouts_section = "\n".join(f"- {w}" for w in d["workouts"])
    else:
        workouts_section = "*(no workouts recorded)*"

    whoop_link = f"[[../../../sports-fitness/Health/WHOOP/2026/daily-{day_str}|View full WHOOP daily note →]]"

    content = f"""# {day_str}

> {whoop_link}

## WHOOP Recovery

| Metric | Value |
|--------|-------|
| Recovery | {fmt(d['recovery'])}{recovery_emoji(d['recovery'])} |
| HRV (RMSSD) | {fmt(d['hrv'])} |
| Resting HR | {fmt(d['rhr'])} |
| SpO₂ | {fmt(d['spo2'])} |
| Skin Temp | {fmt(d['skin_temp'])} |

## Sleep (Main)

| Metric | Value |
|--------|-------|
| In Bed | {fmt(d['sleep_hours'], ' hrs')} |
| Performance | {fmt(d['sleep_perf'])} |
| Efficiency | {fmt(d['sleep_eff'])} |
| Deep (SWS) | {fmt(d['deep_hours'], ' hrs')} |
| REM | {fmt(d['rem_hours'], ' hrs')} |
| Resp Rate | {fmt(d['resp_rate'])} |
| Disturbances | {fmt(d['disturbances'])} |

## Strain

| Metric | Value |
|--------|-------|
| Day Strain | {fmt(d['strain'])} |
| Avg HR | {fmt(d['avg_hr'])} |
| Max HR | {fmt(d['max_hr'])} |
| Calories | {fmt(d['cal_kj'])} |

## Workouts

{workouts_section}

## Notes

"""
    filepath.write_text(content)
    return filepath


def update_sleep_log(day_str, d):
    """Insert or update this day's row in the sleep log."""
    if not SLEEP_LOG.exists():
        print(f"  ⚠ Sleep log not found at {SLEEP_LOG}")
        return

    deep = f"{d['deep_hours']}h" if d["deep_hours"] else "—"
    rem  = f"{d['rem_hours']}h"  if d["rem_hours"]  else "—"
    hrs  = fmt(d["sleep_hours"])
    perf = fmt(d["sleep_perf"])

    new_row = (
        f"| {day_str} | {hrs} | {perf} | "
        f"HRV {fmt(d['hrv'])} · RHR {fmt(d['rhr'])} · Deep {deep} · REM {rem} |"
    )

    log_text = SLEEP_LOG.read_text()

    if re.search(rf"^\| {re.escape(day_str)} \|", log_text, re.MULTILINE):
        log_text = re.sub(
            rf"^\| {re.escape(day_str)} \|.*",
            new_row, log_text, flags=re.MULTILINE
        )
    else:
        # Append before the --- divider (or at end of table)
        if "---\n\n## Weekly Averages" in log_text:
            log_text = log_text.replace(
                "---\n\n## Weekly Averages",
                f"{new_row}\n\n---\n\n## Weekly Averages"
            )
        else:
            log_text = log_text.rstrip() + f"\n{new_row}\n"

    SLEEP_LOG.write_text(log_text)


def update_whoop_index(all_data):
    """Rewrite the summary table in the WHOOP hub index."""
    if not WHOOP_INDEX.exists():
        return

    rows = []
    for day_str, d in sorted(all_data.items(), reverse=True):
        date_label = day_str[5:]  # MM-DD
        recovery = fmt(d["recovery"]) + recovery_emoji(d["recovery"]) if d["recovery"] else "—"
        strain   = fmt(d["strain"])
        sleep    = f"{fmt(d['sleep_hours'])}h · {fmt(d['sleep_perf'])} perf" if d["sleep_hours"] else "—"
        wkts     = ", ".join(d["workouts"]) if d["workouts"] else "—"
        rows.append(
            f"| [[2026/daily-{day_str}\\|{date_label}]] | {recovery} | {strain} | {sleep} | {wkts} |"
        )

    table = (
        "| Date | Recovery | Strain | Sleep | Workouts |\n"
        "|------|----------|--------|-------|----------|\n"
        + "\n".join(rows)
    )

    index_text = WHOOP_INDEX.read_text()
    # Replace the existing table block between the ## 2026 Daily Logs header and the next ---
    index_text = re.sub(
        r"(## 2026 Daily Logs\n\n).*?(\n\n→)",
        rf"\g<1>{table}\g<2>",
        index_text,
        flags=re.DOTALL
    )
    WHOOP_INDEX.write_text(index_text)


# ── main ─────────────────────────────────────────────────────────────────────

def sync_day(day_str):
    filepath = WHOOP_DIR / f"daily-{day_str}.md"
    if not filepath.exists():
        print(f"  ✗ No WHOOP file for {day_str}")
        return None

    d = parse_whoop_file(filepath)
    hist = write_history_file(day_str, d)
    update_sleep_log(day_str, d)

    rec = fmt(d["recovery"])
    slp = fmt(d["sleep_hours"], "h")
    strain = fmt(d["strain_val"])
    wkts = ", ".join(d["workouts"]) if d["workouts"] else "rest day"
    print(f"  ✓ {day_str} · Recovery {rec}  Sleep {slp}  Strain {strain}  [{wkts}]")
    print(f"    → {hist}")
    return d


def main():
    args = sys.argv[1:]

    if "--date" in args:
        idx = args.index("--date")
        days = [args[idx + 1]]
    elif "--all" in args:
        days = sorted(
            p.stem.replace("daily-", "")
            for p in WHOOP_DIR.glob("daily-*.md")
        )
    else:
        days = [date.today().isoformat()]

    print(f"WHOOP folder sync — reading from {WHOOP_DIR}")
    print(f"Processing {len(days)} day(s)...\n")

    all_data = {}
    for day_str in days:
        d = sync_day(day_str)
        if d:
            all_data[day_str] = d

    if all_data:
        update_whoop_index(all_data)
        print(f"\n✓ WHOOP index updated ({len(all_data)} days)")

    print("\nDone.")


if __name__ == "__main__":
    main()
